#!/bin/zsh

for f in allchrom.bed allchrom.bim allchrom.fam; do
cp $f apa.$(basename $f .bed)
cp $f ext_P20.$(basename $f .bed)
cp $f lab.$(basename $f .bed)
cp $f NPlim.$(basename $f .bed)
cp $f occ.$(basename $f .bed)
cp $f org.$(basename $f .bed)
cp $f PBR1.$(basename $f .bed)
cp $f PBR2.$(basename $f .bed)
cp $f PHO1.$(basename $f .bed)
cp $f PHO2.$(basename $f .bed)
cp $f PMEH1.$(basename $f .bed)
cp $f PMEH2.$(basename $f .bed)
cp $f PNZ1.$(basename $f .bed)
cp $f PNZ2.$(basename $f .bed)
cp $f POL1.$(basename $f .bed)
cp $f POL2.$(basename $f .bed)
cp $f sec.$(basename $f .bed)
cp $f sol_Hi.$(basename $f .bed)
cp $f sol_Lo.$(basename $f .bed)
cp $f sol_Mo.$(basename $f .bed)
cp $f sol_VL.$(basename $f .bed)
cp $f sol.$(basename $f .bed)
cp $f stp10.$(basename $f .bed)
cp $f stp20.$(basename $f .bed)
cp $f stp30.$(basename $f .bed)
cp $f stp100.$(basename $f .bed)
cp $f tot.$(basename $f .bed)
cp $f TP1.$(basename $f .bed)
cp $f TP2.$(basename $f .bed)

cp $f apa.$(basename $f .bim)
cp $f ext_P20.$(basename $f .bim)
cp $f lab.$(basename $f .bim)
cp $f NPlim.$(basename $f .bim)
cp $f occ.$(basename $f .bim)
cp $f org.$(basename $f .bim)
cp $f PBR1.$(basename $f .bim)
cp $f PBR2.$(basename $f .bim)
cp $f PHO1.$(basename $f .bim)
cp $f PHO2.$(basename $f .bim)
cp $f PMEH1.$(basename $f .bim)
cp $f PMEH2.$(basename $f .bim)
cp $f PNZ1.$(basename $f .bim)
cp $f PNZ2.$(basename $f .bim)
cp $f POL1.$(basename $f .bim)
cp $f POL2.$(basename $f .bim)
cp $f sec.$(basename $f .bim)
cp $f sol_Hi.$(basename $f .bim)
cp $f sol_Lo.$(basename $f .bim)
cp $f sol_Mo.$(basename $f .bim)
cp $f sol_VL.$(basename $f .bim)
cp $f sol.$(basename $f .bim)
cp $f stp10.$(basename $f .bim)
cp $f stp20.$(basename $f .bim)
cp $f stp30.$(basename $f .bim)
cp $f stp100.$(basename $f .bim)
cp $f tot.$(basename $f .bim)
cp $f TP1.$(basename $f .bim)
cp $f TP2.$(basename $f .bim)

cp $f apa.$(basename $f .fam)
cp $f ext_P20.$(basename $f .fam)
cp $f lab.$(basename $f .fam)
cp $f NPlim.$(basename $f .fam)
cp $f occ.$(basename $f .fam)
cp $f org.$(basename $f .fam)
cp $f PBR1.$(basename $f .fam)
cp $f PBR2.$(basename $f .fam)
cp $f PHO1.$(basename $f .fam)
cp $f PHO2.$(basename $f .fam)
cp $f PMEH1.$(basename $f .fam)
cp $f PMEH2.$(basename $f .fam)
cp $f PNZ1.$(basename $f .fam)
cp $f PNZ2.$(basename $f .fam)
cp $f POL1.$(basename $f .fam)
cp $f POL2.$(basename $f .fam)
cp $f sec.$(basename $f .fam)
cp $f sol_Hi.$(basename $f .fam)
cp $f sol_Lo.$(basename $f .fam)
cp $f sol_Mo.$(basename $f .fam)
cp $f sol_VL.$(basename $f .fam)
cp $f sol.$(basename $f .fam)
cp $f stp10.$(basename $f .fam)
cp $f stp20.$(basename $f .fam)
cp $f stp30.$(basename $f .fam)
cp $f stp100.$(basename $f .fam)
cp $f tot.$(basename $f .fam)
cp $f TP1.$(basename $f .fam)
cp $f TP2.$(basename $f .fam)

done


